# Generated by Django 4.2 on 2023-04-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0027_remove_buku_cover_buku_dokumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='kelompok_id',
        ),
    ]
