# Generated by Django 4.0.3 on 2023-04-20 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0028_remove_buku_kelompok_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='key_enkripsi',
            field=models.FileField(default=django.utils.timezone.now, upload_to='key/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='dokumen',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
