# Generated by Django 4.2 on 2023-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0030_buku_encpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='jumlah',
        ),
    ]
